title: "Nisha Koppa"
description: "A PhD student; somewhere between research, data, policy, and everyday stories about food !!"
theme: jekyll-theme-cayman   
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
include: ["assets"]       
